"""Generate a bounded, relative-link Markdown gallery from the local catalog.

This module only writes its own docs pages. It never changes cases, images,
source documents, or indexes. Calling build_gallery under the library writer lock
lets catalog rebuilding and gallery publication share the same transaction scope.
"""

from __future__ import annotations

import hashlib
import html
import json
import os
from pathlib import Path, PurePosixPath
import posixpath
import re
import tempfile
from urllib.parse import quote


MARKER = "<!-- Generated by scripts/gallery.py; edit authoritative JSON, then rebuild. -->"
PAGE_SIZE = 100


def _read(path, default):
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else default


def _localized(value, fallback=""):
    if isinstance(value, dict):
        return str(value.get("zh") or value.get("en") or fallback)
    return str(value if value is not None else fallback)


def _text(value):
    """Make imported text inert inside Markdown headings, tables, and labels."""
    value = " ".join(_localized(value).split())
    value = html.escape(value, quote=False)
    return re.sub(r"([\\`*_{}\[\]()#+.!|~])", r"\\\1", value)


def _relative_link(target, document, anchor=None):
    """Only repository-relative paths are allowed in generated links."""
    target = str(target)
    path = PurePosixPath(target)
    if not target or path.is_absolute() or ".." in path.parts or "\\" in target or ":" in target:
        raise ValueError("Expected repository-relative path: " + target)
    relative = posixpath.relpath(path.as_posix(), posixpath.dirname(document) or ".")
    result = quote(relative, safe="/-._~")
    if anchor:
        result += "#" + quote(str(anchor).removeprefix("#"), safe="-._~")
    return result


def _source_number(entry):
    """Use a source number only when its stable ID digest proves the extraction."""
    case_id = str(entry["case_id"])
    for source in entry.get("sources", []):
        prefix = "case-" + str(source) + "-"
        if not case_id.startswith(prefix):
            continue
        match = re.fullmatch(r"([0-9]+)-([0-9a-f]{12})", case_id[len(prefix):])
        if match:
            source_id, digest = match.groups()
            expected = hashlib.sha256((str(source) + "\0" + source_id).encode("utf-8")).hexdigest()[:12]
            if digest == expected:
                return str(source), source_id
    return None


def _sort_key(entry):
    numeric = _source_number(entry)
    if numeric:
        return (0, numeric[0], int(numeric[1]), entry["case_id"])
    return (1, str(entry["case_id"]), 0, "")


def _case_link(entry, document):
    case_id, version = str(entry["case_id"]), str(entry["version"])
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", case_id) or ".." in case_id:
        raise ValueError("Invalid case ID: " + case_id)
    if not re.fullmatch(r"v[1-9][0-9]*", version):
        raise ValueError("Invalid case version: " + version)
    numeric = _source_number(entry)
    # Show source names when a catalog grows beyond a single upstream source.
    identifier = (numeric[0] + " #" + numeric[1]) if numeric else case_id
    label = _text(entry.get("title") or case_id) + " \u00b7 " + _text(version)
    link = _relative_link("cases/" + case_id + "/" + version + ".md", document)
    return "- [" + label + "](" + link + ") \u2014 " + _text(identifier)


def _slug(value, fallback):
    value = str(value or "")
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{0,70}", value):
        return value
    return "category-" + hashlib.sha256(fallback.encode("utf-8")).hexdigest()[:16]


def _category_specs(root, entries):
    taxonomy = _read(root / "metadata" / "taxonomy.json", {})
    aliases = taxonomy.get("aliases", {})
    names, used_files, specs = set(), set(), []
    for record in taxonomy.get("categories", []):
        if isinstance(record, dict):
            title = _localized(record.get("title"), record.get("value", record.get("id", "")))
            slug = _slug(record.get("id"), title)
            original = record.get("value", title)
            search_names = {title, str(original)}
            alias = aliases.get(original)
            if isinstance(alias, str):
                search_names.add(alias)
        else:
            title, search_names = str(record), {str(record)}
            slug = _slug(None, title)
        if not title or title in names:
            continue
        if slug in used_files:
            slug += "-" + hashlib.sha256(title.encode("utf-8")).hexdigest()[:8]
        specs.append({"title": title, "slug": slug, "names": search_names})
        names.add(title)
        used_files.add(slug)
    covered = {name for spec in specs for name in spec["names"]}
    actual = sorted({str(category) for entry in entries for category in entry.get("categories", [])})
    for title in actual:
        if title not in covered:
            slug = _slug(None, title)
            specs.append({"title": title, "slug": slug, "names": {title}})
            covered.add(title)
    if any(not entry.get("categories") for entry in entries):
        specs.append({"title": "\u672a\u5206\u7c7b", "slug": "uncategorized", "names": set()})
    return specs


def _page(title):
    return [MARKER, "", "# " + _text(title), ""]


def _atomic_page(path, content):
    data = content.encode("utf-8")
    if path.exists():
        current = path.read_bytes()
        if current == data:
            return False
        if not current.startswith(MARKER.encode("utf-8")):
            raise FileExistsError("Refusing to overwrite a non-generated document: " + str(path))
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(prefix=".gallery-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as out:
            out.write(data)
            out.flush()
            os.fsync(out.fileno())
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)
    return True


def build_gallery(root, catalog):
    """Build docs/gallery.md, categories, numbered parts, and templates.md.

    Entries in catalog are metadata only; no complete prompts or images are read.
    Templates link to existing complete source documents and local cover images.
    Missing template fixtures are valid. Existing unrelated docs are untouched.
    All pages are rendered before writes so malformed paths do not half-render.
    """
    root = Path(root)
    entries = sorted(catalog.get("cases", []), key=_sort_key)
    if len({entry["case_id"] for entry in entries}) != len(entries):
        raise ValueError("Duplicate case ID in catalog")
    specs = _category_specs(root, entries)
    pages = {}
    for spec in specs:
        document = "docs/categories/" + spec["slug"] + ".md"
        selected = [entry for entry in entries if (set(entry.get("categories", [])) & spec["names"] if spec["names"] else not entry.get("categories"))]
        spec["count"] = len(selected)
        lines = _page(spec["title"])
        lines += ["[\u8fd4\u56de\u753b\u5eca\u603b\u89c8](../gallery.md)", "",
                  "\u5171 " + str(len(selected)) + " \u4e2a\u6848\u4f8b\u3002\u70b9\u51fb\u6807\u9898\u67e5\u770b\u672c\u5e93\u56fe\u7247\u4e0e\u5b8c\u6574\u63d0\u793a\u8bcd\u3002", ""]
        lines += [_case_link(entry, document) for entry in selected]
        if not selected:
            lines += ["\u8be5\u5206\u7c7b\u6682\u65e0\u5df2\u6536\u5f55\u6848\u4f8b\u3002"]
        pages[document] = "\n".join(lines) + "\n"
    chunks = [entries[start:start + PAGE_SIZE] for start in range(0, len(entries), PAGE_SIZE)]
    for number, chunk in enumerate(chunks, 1):
        document = "docs/gallery-part-" + str(number) + ".md"
        lines = _page("\u5168\u90e8\u6848\u4f8b \u00b7 \u7b2c " + str(number) + " \u518c")
        navigation = ["[\u753b\u5eca\u603b\u89c8](gallery.md)"]
        if number > 1:
            navigation.append("[\u4e0a\u4e00\u518c](gallery-part-" + str(number - 1) + ".md)")
        if number < len(chunks):
            navigation.append("[\u4e0b\u4e00\u518c](gallery-part-" + str(number + 1) + ".md)")
        lines += [" | ".join(navigation), "", "\u672c\u518c " + str(len(chunk)) + " \u4e2a\u6848\u4f8b\u3002\u6807\u9898\u94fe\u63a5\u56fa\u5b9a\u5230\u6240\u793a\u7248\u672c\u3002", ""]
        lines += [_case_link(entry, document) for entry in chunk]
        pages[document] = "\n".join(lines) + "\n"
    template_index = _read(root / "indexes" / "templates.json", {})
    templates = template_index.get("templates", [])
    lines = _page("\u63d0\u793a\u8bcd\u6a21\u677f")
    lines += ["[\u8fd4\u56de\u753b\u5eca\u603b\u89c8](gallery.md)", "",
              "\u5171 " + str(len(templates)) + " \u4e2a\u6a21\u677f\u3002\u8fd9\u91cc\u5c55\u793a\u7b80\u4ecb\u548c\u672c\u5e93\u5c01\u9762\uff1b\u5b8c\u6574\u6a21\u677f\u4fdd\u7559\u5728\u5df2\u5f52\u6863\u7684\u539f\u6587\u6587\u6863\u4e2d\u3002", ""]
    for template in templates:
        title = _localized(template.get("title"), template.get("id", "Template"))
        lines += ["## " + _text(title), ""]
        description = _localized(template.get("description"))
        if description:
            lines += [_text(description), ""]
        cover = template.get("cover")
        if cover:
            lines += ["![" + _text(title) + "](" + _relative_link(cover, "docs/templates.md") + ")", ""]
        document = template.get("document") or template_index.get("document")
        if document:
            target = _relative_link(document, "docs/templates.md", template.get("anchor"))
            lines += ["[\u67e5\u770b\u5b8c\u6574\u6a21\u677f](" + target + ")", ""]
        else:
            lines += ["\u5c1a\u65e0\u5b8c\u6574\u6a21\u677f\u6587\u6863\u3002", ""]
    if not templates:
        lines += ["\u6682\u65e0\u5df2\u5f52\u6863\u6a21\u677f\u3002", ""]
    pages["docs/templates.md"] = "\n".join(lines) + "\n"
    lines = _page("\u4e2a\u4eba\u89c6\u89c9\u8d44\u6599\u5e93\u753b\u5eca")
    lines += ["[\u8fd4\u56de\u4ed3\u5e93\u9996\u9875](../README.md)", "",
              "\u5df2\u6536\u5f55 **" + str(len(entries)) + "** \u4e2a\u6848\u4f8b\uff0c**" + str(len(specs)) + "** \u4e2a\u5bfc\u822a\u5206\u7c7b\uff0c**" + str(len(templates)) + "** \u4e2a\u6a21\u677f\u3002", "",
              "\u6309\u5206\u7c7b\u6216\u5206\u518c\u6d4f\u89c8\uff0c\u70b9\u51fb\u6848\u4f8b\u6807\u9898\u67e5\u770b\u672c\u5e93\u56fe\u7247\u548c\u5b8c\u6574\u539f\u59cb\u63d0\u793a\u8bcd\u3002", "",
              "[\u63d0\u793a\u8bcd\u6a21\u677f](templates.md)", "", "## \u5206\u7c7b\u6d4f\u89c8", "",
              "| \u5206\u7c7b | \u6848\u4f8b\u6570 |", "| --- | ---: |"]
    for spec in specs:
        target = "categories/" + spec["slug"] + ".md"
        lines.append("| [" + _text(spec["title"]) + "](" + target + ") | " + str(spec["count"]) + " |")
    lines += ["", "## \u5168\u90e8\u6848\u4f8b", "", "\u6bcf\u518c\u6700\u591a " + str(PAGE_SIZE) + " \u4e2a\u6848\u4f8b\uff0c\u4e0b\u5217\u5206\u518c\u5408\u8ba1\u8986\u76d6\u5168\u90e8\u5df2\u6536\u5f55\u6848\u4f8b\u3002", ""]
    for number, chunk in enumerate(chunks, 1):
        lines.append("- [\u7b2c " + str(number) + " \u518c](gallery-part-" + str(number) + ".md)\uff08" + str(len(chunk)) + " \u4e2a\u6848\u4f8b\uff09")
    if not entries:
        lines += ["\u6682\u65e0\u5df2\u6536\u5f55\u6848\u4f8b\u3002"]
    lines += ["", "## \u6700\u8fd1\u6536\u5f55", ""]
    recent = sorted(entries, key=lambda entry: (str(entry.get("archived_at", ""))[:10], _sort_key(entry)), reverse=True)[:12]
    lines += [_case_link(entry, "docs/gallery.md") for entry in recent]
    pages["docs/gallery.md"] = "\n".join(lines) + "\n"
    # Preflight ownership before publishing any generated page.
    for document in pages:
        path = root / document
        if path.exists() and not path.read_bytes().startswith(MARKER.encode("utf-8")):
            raise FileExistsError("Refusing to overwrite a non-generated document: " + str(path))
    written = [document for document, content in pages.items() if _atomic_page(root / document, content)]
    return {"cases": len(entries), "categories": len(specs), "parts": len(chunks),
            "templates": len(templates), "written": written}
