"""Generate a bounded, relative-link Markdown gallery from the local catalog.

This module writes its own docs pages and an explicitly marked README block.
It never changes cases, images, source documents, or indexes. Calling build_gallery under the library writer lock
lets catalog rebuilding and gallery publication share the same transaction scope.
"""

from __future__ import annotations

import hashlib
import html
import json
import os
from pathlib import Path, PurePosixPath
import posixpath
import re
import tempfile
from urllib.parse import quote


MARKER = "<!-- Generated by scripts/gallery.py; edit authoritative JSON, then rebuild. -->"
PAGE_SIZE = 25
README_START = "<!-- VISUAL-LIBRARY-GALLERY:START -->"
README_END = "<!-- VISUAL-LIBRARY-GALLERY:END -->"


def _read(path, default):
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else default


def _localized(value, fallback=""):
    if isinstance(value, dict):
        return str(value.get("zh") or value.get("en") or fallback)
    return str(value if value is not None else fallback)


def _text(value):
    """Make imported text inert inside Markdown headings, tables, and labels."""
    value = " ".join(_localized(value).split())
    value = html.escape(value, quote=False)
    return re.sub(r"([\\`*_{}\[\]()#+.!|~])", r"\\\1", value)


def _relative_link(target, document, anchor=None):
    """Only repository-relative paths are allowed in generated links."""
    target = str(target)
    path = PurePosixPath(target)
    if not target or path.is_absolute() or ".." in path.parts or "\\" in target or ":" in target:
        raise ValueError("Expected repository-relative path: " + target)
    relative = posixpath.relpath(path.as_posix(), posixpath.dirname(document) or ".")
    result = quote(relative, safe="/-._~")
    if anchor:
        result += "#" + quote(str(anchor).removeprefix("#"), safe="-._~")
    return result


def _source_number(entry):
    """Use a source number only when its stable ID digest proves the extraction."""
    case_id = str(entry["case_id"])
    for source in entry.get("sources", []):
        prefix = "case-" + str(source) + "-"
        if not case_id.startswith(prefix):
            continue
        match = re.fullmatch(r"([0-9]+)-([0-9a-f]{12})", case_id[len(prefix):])
        if match:
            source_id, digest = match.groups()
            expected = hashlib.sha256((str(source) + "\0" + source_id).encode("utf-8")).hexdigest()[:12]
            if digest == expected:
                return str(source), source_id
    return None


def _sort_key(entry):
    numeric = _source_number(entry)
    if numeric:
        return (0, numeric[0], int(numeric[1]), entry["case_id"])
    return (1, str(entry["case_id"]), 0, "")


def _case_link(entry, document):
    case_id, version = str(entry["case_id"]), str(entry["version"])
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", case_id) or ".." in case_id:
        raise ValueError("Invalid case ID: " + case_id)
    if not re.fullmatch(r"v[1-9][0-9]*", version):
        raise ValueError("Invalid case version: " + version)
    numeric = _source_number(entry)
    # Show source names when a catalog grows beyond a single upstream source.
    identifier = (numeric[0] + " #" + numeric[1]) if numeric else case_id
    label = _text(entry.get("title") or case_id) + " \u00b7 " + _text(version)
    link = _relative_link("cases/" + case_id + "/" + version + ".md", document)
    return "- [" + label + "](" + link + ") \u2014 " + _text(identifier)


def _html_text(value):
    return html.escape(" ".join(_localized(value).split()), quote=True)


def _image(path, document, title, width):
    relative = html.escape(_relative_link(path, document), quote=True)
    return '<img src="' + relative + '" alt="' + _html_text(title) + '" width="' + str(width) + '">'


def _cards(cards):
    """GitHub-compatible three-column HTML with no CSS or scripts."""
    if not cards:
        return []
    lines = ["<table>"]
    for start in range(0, len(cards), 3):
        lines.append("<tr>")
        for card in cards[start:start + 3]:
            lines.append('<td width="33%" align="center" valign="top">' + card + "</td>")
        for _ in range(3 - len(cards[start:start + 3])):
            lines.append('<td width="33%" align="center" valign="top"></td>')
        lines.append("</tr>")
    lines += ["</table>", ""]
    return lines



RECORD_LABELS = {"case": "原图文案例", "style_reference": "风格参考", "keyword_reference": "关键词资料"}


def _record_label(entry):
    kind = entry.get("record_type") or "case"
    return RECORD_LABELS.get(kind, "其他资料")


def _review_label(entry):
    status = entry.get("review_status") or "needs_review"
    if entry.get("effective_status") == "missing_inputs" or status == "missing_inputs":
        return "缺少必要输入图：请先查看详情并补齐参考图"
    if status in {"needs_review", "untagged", "unknown"}:
        return "待复核：尚无补充核查，不代表必要输入已齐全"
    if status in {"verified", "reviewed", "complete"}:
        return "已记录补充核查结果；以详情中的输入要求为准"
    return "核查状态：" + str(status)


def _summary(entries):
    counts = {label: sum(_record_label(entry) == label for entry in entries)
              for label in RECORD_LABELS.values()}
    other = len(entries) - sum(counts.values())
    if other:
        counts["其他资料"] = other
    pending = sum((entry.get("review_status") or "needs_review") in {"needs_review", "untagged", "unknown"} for entry in entries)
    missing = sum(entry.get("effective_status") == "missing_inputs" or entry.get("review_status") == "missing_inputs" for entry in entries)
    return (" · ".join(label + " " + str(count) for label, count in counts.items() if count) +
            "。待复核 " + str(pending) + "；缺少必要输入图 " + str(missing) +
            "。")


def _facet_pages(entries):
    pages = {}
    for document, title, fields in [
        ("docs/models/index.md", "按模型浏览", [("model_family", "模型")]),
        ("docs/topics/index.md", "艺术家、流派与材质", [("artists", "艺术家"), ("movements", "流派"), ("materials", "材质"), ("techniques", "技法")])]:
        lines = _page(title) + ["[返回画廊总览](../gallery.md)", "", "标签用于检索；未标注表示来源或补充标注未提供，并非不适用。", ""]
        for field, label in fields:
            groups = {}
            for entry in entries:
                values = entry.get(field) or (["unknown"] if field == "model_family" else [])
                if isinstance(values, str):
                    values = [values]
                for value in sorted(set(values)):
                    groups.setdefault(value, []).append(entry)
            lines += ["## " + label, ""]
            if not groups:
                lines += ["暂无已标注条目。", ""]
            for value, selected in sorted(groups.items()):
                lines += ["### " + _text("尚未标注" if value == "unknown" else value) + " · " + str(len(selected)), ""]
                lines += [_case_link(entry, document) + " — " + _text(_record_label(entry)) + "；" + _text(_review_label(entry)) for entry in selected]
                lines.append("")
        pages[document] = "\n".join(lines) + "\n"
    return pages


def _case_card(entry, content, document):
    # Reuse the strict identity validation used for Markdown links.
    _case_link(entry, document)
    target = _relative_link("cases/" + entry["case_id"] + "/" + entry["version"] + ".md", document)
    title = _localized(entry.get("title"), entry["case_id"])
    label = _html_text(title) + " \u00b7 " + _html_text(entry["version"])
    anchor = '<a href="' + html.escape(target, quote=True) + '">'
    fragments = []
    cover = content.get("cover")
    if cover:
        fragments += [anchor + _image(cover, document, title, 220) + "</a><br>"]
    fragments += [anchor + "<strong>" + label + "</strong></a>"]
    numeric = _source_number(entry)
    identifier = (numeric[0] + " #" + numeric[1]) if numeric else entry["case_id"]
    fragments += ["<br><sub>" + _html_text(identifier) + "</sub>"]
    fragments += ["<br><sub>" + _html_text(_record_label(entry)) + " · " + _html_text(entry.get("model_family") or "模型尚未标注") + "</sub>", "<br><sub>" + _html_text(_review_label(entry)) + "</sub>"]
    return "".join(fragments)


def _category_card(spec, document):
    target = _relative_link("docs/categories/" + spec["slug"] + ".md", document)
    anchor = '<a href="' + html.escape(target, quote=True) + '">'
    fragments = []
    if spec.get("cover"):
        fragments += [anchor + _image(spec["cover"], document, spec["title"], 220) + "</a><br>"]
    fragments += [anchor + "<strong>" + _html_text(spec["title"]) + "</strong></a>",
                  "<br><sub>" + str(spec["count"]) + " 条资料</sub>"]
    if spec.get("description"):
        fragments += ["<br>" + _html_text(spec["description"])]
    return "".join(fragments)


def _contents(root, entries):
    """Read the exact catalog version once; missing JSON is a fixture fallback."""
    result = {}
    for entry in entries:
        _case_link(entry, "docs/gallery.md")
        path = root / "cases" / entry["case_id"] / (entry["version"] + ".json")
        content = _read(path, {})
        assets = []
        role_overrides = {item["index"]: item["role"] for item in entry.get("asset_roles", []) if "index" in item and "role" in item}
        for index, original_asset in enumerate(content.get("assets", [])):
            asset = dict(original_asset)
            asset["role"] = role_overrides.get(index, asset.get("role", "unknown"))
            relative = asset.get("path")
            if relative:
                _relative_link(relative, "docs/gallery.md")
                if (root / relative).is_file():
                    assets.append(asset)
        content["local_assets"] = assets
        preferred = [asset for asset in assets if asset.get("role") in {"output", "example"}] or assets
        content["cover"] = preferred[0]["path"] if preferred else None
        result[entry["case_id"]] = content
    return result


def _case_section(entry, content, document):
    title = _localized(entry.get("title"), entry["case_id"])
    lines = ["## " + _text(title) + " \u00b7 " + _text(entry["version"]), "",
             _case_link(entry, document), "",
             _text(_record_label(entry)) + " · " + _text(entry.get("model_family") or "模型尚未标注"), "",
             "**" + _text(_review_label(entry)) + "**", ""]
    if entry.get("review_note"):
        lines += [_text(entry["review_note"]), ""]
    for asset in content.get("local_assets", []):
        role = {"input": "输入参考图", "output": "输出示例图", "example": "示例图", "reference": "风格参考图"}.get(asset.get("role"), "图片角色尚未确认")
        lines += ["**" + role + "**", "", _image(asset["path"], document, title, 760), ""]
    prompt = content.get("prompt")
    if isinstance(prompt, str):
        fence = "`" * max(3, max((len(match.group(0)) + 1 for match in re.finditer(r"`+", prompt)), default=3))
        lines += ["<details>", "<summary>\u5c55\u5f00\u5b8c\u6574\u63d0\u793a\u8bcd</summary>", "",
                  fence + "text", prompt, fence, "", "</details>", ""]
    return lines


def _slug(value, fallback):
    value = str(value or "")
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{0,70}", value):
        return value
    return "category-" + hashlib.sha256(fallback.encode("utf-8")).hexdigest()[:16]


def _category_specs(root, entries):
    taxonomy = _read(root / "metadata" / "taxonomy.json", {})
    aliases = taxonomy.get("aliases", {})
    names, used_files, specs = set(), set(), []
    for record in taxonomy.get("categories", []):
        if isinstance(record, dict):
            title = _localized(record.get("title"), record.get("value", record.get("id", "")))
            slug = _slug(record.get("id"), title)
            original = record.get("value", title)
            search_names = {title, str(original)}
            alias = aliases.get(original)
            if isinstance(alias, str):
                search_names.add(alias)
        else:
            title, search_names = str(record), {str(record)}
            slug = _slug(None, title)
        if not title or title in names:
            continue
        if slug in used_files:
            slug += "-" + hashlib.sha256(title.encode("utf-8")).hexdigest()[:8]
        description = _localized(record.get("description")) if isinstance(record, dict) else ""
        specs.append({"title": title, "slug": slug, "names": search_names, "description": description})
        names.add(title)
        used_files.add(slug)
    covered = {name for spec in specs for name in spec["names"]}
    actual = sorted({str(category) for entry in entries for category in entry.get("categories", [])})
    for title in actual:
        if title not in covered:
            slug = _slug(None, title)
            specs.append({"title": title, "slug": slug, "names": {title}})
            covered.add(title)
    if any(not entry.get("categories") for entry in entries):
        specs.append({"title": "\u672a\u5206\u7c7b", "slug": "uncategorized", "names": set()})
    return specs


def _page(title):
    return [MARKER, "", "# " + _text(title), ""]


def _atomic_page(path, content, readme_block=False):
    data = content.encode("utf-8")
    if path.exists():
        current = path.read_bytes()
        if current == data:
            return False
        if not readme_block and not current.startswith(MARKER.encode("utf-8")):
            raise FileExistsError("Refusing to overwrite a non-generated document: " + str(path))
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(prefix=".gallery-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as out:
            out.write(data)
            out.flush()
            os.fsync(out.fileno())
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)
    return True


def _readme_content(root, entries, specs, templates, recent, contents):
    path = root / "README.md"
    if not path.is_file():
        return None
    original = path.read_bytes().decode("utf-8")
    if README_START not in original and README_END not in original:
        return None
    if original.count(README_START) != 1 or original.count(README_END) != 1:
        raise ValueError("README gallery requires exactly one START/END marker pair")
    start = original.index(README_START) + len(README_START)
    end = original.index(README_END)
    if end < start:
        raise ValueError("README gallery markers are reversed")
    newline = "\r\n" if "\r\n" in original else "\n"
    lines = [""]
    if (root / "assets" / "banner.svg").is_file():
        lines += ["![\u4e2a\u4eba\u89c6\u89c9\u8d44\u6599\u5e93](assets/banner.svg)", ""]
    lines += ["**" + str(len(entries)) + " 条资料 \u00b7 " + str(len(specs)) + " \u4e2a\u5206\u7c7b \u00b7 " + str(len(templates)) + " \u4e2a\u6a21\u677f**", "",
              "[\u6253\u5f00\u5b8c\u6574\u753b\u5eca](docs/gallery.md) \u00b7 [\u63d0\u793a\u8bcd\u6a21\u677f](docs/templates.md)", "",
              "### \u5206\u7c7b\u6d4f\u89c8", ""]
    navigation = "[按模型浏览](docs/models/index.md) · [艺术家、流派与材质](docs/topics/index.md)"
    if (root / 'docs/collection-status.md').is_file():
        navigation += " · [复核说明](docs/collection-status.md)"
    if (root / 'docs/pdf-keywords.md').is_file():
        navigation += " · [PDF关键词补遗](docs/pdf-keywords.md)"
    lines[-2:-2] = [_summary(entries), "", navigation, ""]
    lines += _cards([_category_card(spec, "README.md") for spec in specs])
    lines += ["### \u6700\u8fd1\u6536\u5f55", ""]
    lines += _cards([_case_card(entry, contents[entry["case_id"]], "README.md") for entry in recent[:6]])
    # Only replace bytes between the existing markers, including their interior
    # newlines. Prefix, suffix, marker bytes, BOM, and outside line endings survive.
    replacement = newline.join(lines) + newline
    return original[:start] + replacement + original[end:]


def build_gallery(root, catalog):
    """Build docs/gallery.md, categories, numbered parts, and templates.md.

    Catalog versions supply immutable prompts and local image references.
    Templates link to existing complete source documents and local cover images.
    Missing template fixtures are valid. Existing unrelated docs are untouched.
    All pages are rendered before writes so malformed paths do not half-render.
    """
    root = Path(root)
    entries = sorted(catalog.get("cases", []), key=_sort_key)
    if len({entry["case_id"] for entry in entries}) != len(entries):
        raise ValueError("Duplicate case ID in catalog")
    specs = _category_specs(root, entries)
    contents = _contents(root, entries)
    style = _read(root / "metadata" / "gallery-style.json", {})
    pages = _facet_pages(entries)
    for spec in specs:
        document = "docs/categories/" + spec["slug"] + ".md"
        selected = [entry for entry in entries if (set(entry.get("categories", [])) & spec["names"] if spec["names"] else not entry.get("categories"))]
        spec["count"] = len(selected)
        configured = style.get("category_covers", {}).get(spec["slug"], {})
        cover = configured.get("path")
        if cover:
            _relative_link(cover, document)
        spec["cover"] = cover if cover and (root / cover).is_file() else next((contents[entry["case_id"]]["cover"] for entry in selected if contents[entry["case_id"]].get("cover")), None)
        if configured.get("description"):
            spec["description"] = _localized(configured["description"])
        lines = _page(spec["title"])
        lines += ["[\u8fd4\u56de\u753b\u5eca\u603b\u89c8](../gallery.md)", "",
                  "\u5171 " + str(len(selected)) + " 条资料\u3002\u70b9\u51fb\u6807\u9898\u67e5\u770b本库图片与原始内容\u3002", ""]
        lines += _cards([_case_card(entry, contents[entry["case_id"]], document) for entry in selected])
        if not selected:
            lines += ["\u8be5\u5206\u7c7b\u6682\u65e0已收录资料\u3002"]
        pages[document] = "\n".join(lines) + "\n"
    chunks = [entries[start:start + PAGE_SIZE] for start in range(0, len(entries), PAGE_SIZE)]
    for number, chunk in enumerate(chunks, 1):
        document = "docs/gallery-part-" + str(number) + ".md"
        lines = _page("全部资料 \u00b7 \u7b2c " + str(number) + " \u518c")
        navigation = ["[\u753b\u5eca\u603b\u89c8](gallery.md)"]
        if number > 1:
            navigation.append("[\u4e0a\u4e00\u518c](gallery-part-" + str(number - 1) + ".md)")
        if number < len(chunks):
            navigation.append("[\u4e0b\u4e00\u518c](gallery-part-" + str(number + 1) + ".md)")
        lines += [" | ".join(navigation), "", "\u672c\u518c " + str(len(chunk)) + " 条资料\u3002\u6807\u9898\u94fe\u63a5\u56fa\u5b9a\u5230\u6240\u793a\u7248\u672c\u3002", ""]
        for entry in chunk:
            lines += _case_section(entry, contents[entry["case_id"]], document)
        pages[document] = "\n".join(lines) + "\n"
    template_index = _read(root / "indexes" / "templates.json", {})
    templates = template_index.get("templates", [])
    lines = _page("\u63d0\u793a\u8bcd\u6a21\u677f")
    lines += ["[\u8fd4\u56de\u753b\u5eca\u603b\u89c8](gallery.md)", "",
              "\u5171 " + str(len(templates)) + " \u4e2a\u6a21\u677f\u3002\u8fd9\u91cc\u5c55\u793a\u7b80\u4ecb\u548c\u672c\u5e93\u5c01\u9762\uff1b\u5b8c\u6574\u6a21\u677f\u4fdd\u7559\u5728\u5df2\u5f52\u6863\u7684\u539f\u6587\u6587\u6863\u4e2d\u3002", ""]
    for template in templates:
        title = _localized(template.get("title"), template.get("id", "Template"))
        lines += ["## " + _text(title), ""]
        description = _localized(template.get("description"))
        if description:
            lines += [_text(description), ""]
        cover = template.get("cover")
        if cover:
            lines += ["![" + _text(title) + "](" + _relative_link(cover, "docs/templates.md") + ")", ""]
        document = template.get("document") or template_index.get("document")
        if document:
            target = _relative_link(document, "docs/templates.md", template.get("anchor"))
            lines += ["[\u67e5\u770b\u5b8c\u6574\u6a21\u677f](" + target + ")", ""]
        else:
            lines += ["\u5c1a\u65e0\u5b8c\u6574\u6a21\u677f\u6587\u6863\u3002", ""]
    if not templates:
        lines += ["\u6682\u65e0\u5df2\u5f52\u6863\u6a21\u677f\u3002", ""]
    pages["docs/templates.md"] = "\n".join(lines) + "\n"
    lines = _page("\u4e2a\u4eba\u89c6\u89c9\u8d44\u6599\u5e93\u753b\u5eca")
    lines += ["[\u8fd4\u56de\u4ed3\u5e93\u9996\u9875](../README.md)", "",
              "\u5df2\u6536\u5f55 **" + str(len(entries)) + "** 条资料\uff0c**" + str(len(specs)) + "** \u4e2a\u5bfc\u822a\u5206\u7c7b\uff0c**" + str(len(templates)) + "** \u4e2a\u6a21\u677f\u3002", "",
              "\u6309\u5206\u7c7b\u6216\u5206\u518c\u6d4f\u89c8\uff0c\u70b9\u51fb\u6848\u4f8b\u6807\u9898\u67e5\u770b本库图片和原始内容；复用前请查看输入要求与核查状态\u3002", "",
              "[\u63d0\u793a\u8bcd\u6a21\u677f](templates.md)", "", "## \u5206\u7c7b\u6d4f\u89c8", ""]
    lines[4:4] = [_summary(entries), "", "[按模型浏览](models/index.md) · [艺术家、流派与材质](topics/index.md)", ""]
    lines += _cards([_category_card(spec, "docs/gallery.md") for spec in specs])
    lines += ["", "## 全部资料", "", "\u6bcf\u518c\u6700\u591a " + str(PAGE_SIZE) + " 条资料\uff0c\u4e0b\u5217\u5206\u518c\u5408\u8ba1\u8986\u76d6\u5168\u90e8已收录资料\u3002", ""]
    for number, chunk in enumerate(chunks, 1):
        lines.append("- [\u7b2c " + str(number) + " \u518c](gallery-part-" + str(number) + ".md)\uff08" + str(len(chunk)) + " 条资料\uff09")
    if not entries:
        lines += ["\u6682\u65e0已收录资料\u3002"]
    lines += ["", "## \u6700\u8fd1\u6536\u5f55", ""]
    recent = sorted(entries, key=lambda entry: (str(entry.get("archived_at", ""))[:10], _sort_key(entry)), reverse=True)[:12]
    lines += _cards([_case_card(entry, contents[entry["case_id"]], "docs/gallery.md") for entry in recent])
    pages["docs/gallery.md"] = "\n".join(lines) + "\n"
    readme = _readme_content(root, entries, specs, templates, recent, contents)
    # Preflight ownership before publishing any generated page.
    for document in pages:
        path = root / document
        if path.exists() and not path.read_bytes().startswith(MARKER.encode("utf-8")):
            raise FileExistsError("Refusing to overwrite a non-generated document: " + str(path))
    written = [document for document, content in pages.items() if _atomic_page(root / document, content)]
    if readme is not None and _atomic_page(root / "README.md", readme, readme_block=True):
        written.append("README.md")
    return {"cases": len(entries), "categories": len(specs), "parts": len(chunks),
            "templates": len(templates), "written": written}
